name;
amplitude;
data = importdata(name);
w = data(:,1);
t = data(:,2)/1000;
figure;
grid on;
hold on;
plot(t,w);
u = (ones(length(w),1))*amplitude;
expId = iddata(w,u,0.01);
expId.Tstart = 0;
E = resid(expId,tf1);
res = E.OutputData;
[TF,L,U,C] = isoutlier(res,'percentiles',[10,99]);
figure;
grid on;
hold on;
plot(t,res,'o',t(TF),res(TF),'x',t,L*ones(length(w),1),t,U*ones(length(w),1),t,C*ones(length(w),1));
figure;
grid on;
hold on; 
plot(t,w,t(TF),w(TF),'x');
MatrixOutliers = [w,t,TF];